import sqlite3
banco = sqlite3.connect("P2Info.db")
cursor = banco.cursor()
#cursor.execute("CREATE TABLE alunos(matr integer, nome text, n1 float, n2 float, mg float, cd_sit integer)")
cursor.execute("INSERT INTO alunos VALUES(10, 'Ana ', 7.0, 5.0, 0.0, 'nenhuma')")
cursor.execute("INSERT INTO alunos VALUES(20, 'Bia ', 8.0, 6.0, 0.0, 'nenhuma')")
cursor.execute("INSERT INTO alunos VALUES (30, 'Daniel ', 5.0, 4.0, 0.0, 'nenhuma')")
cursor.execute("INSERT INTO alunos VALUES (40, 'Elias ', 9.0, 8.0, 0.0, 'nenhuma')")
cursor.execute("INSERT INTO alunos VALUES (50, 'George', 2.0, 3.0, 0.0, 'nenhuma')")
cursor.execute("INSERT INTO alunos VALUES (60, 'Ingrid ', 7.0, 7.0, 0.0, 'nenhuma')")
cursor.execute("INSERT INTO alunos VALUES (70, 'Katia ', 2.0, 1.0, 0.0, 'nenhuma')")
cursor.execute("INSERT INTO alunos VALUES (80, 'Maria ', 4.0, 5.0, 0.0, 'nenhuma')")
cursor.execute("INSERT INTO alunos VALUES (90, 'Olga ', 4.0, 5.0, 0.0, 'nenhuma')")
cursor.execute("INSERT INTO alunos VALUES (99, 'Zorro ', 9.0, 9.0, 0.0, 'nenhuma')")
banco.commit()
cursor.execute("SELECT * FROM alunos")
print(cursor.fetchall())
cursor.execute("UPDATE aluno SET mg = (2*n1 + 3*n2)/5")
cursor.execute("SELECT * FROM alunos")
print(cursor.fetchall())
cursor.execute("UPDATE alunos SET sit = 'Aprov' WHERE mg >= 6")
cursor.execute("UPDATE alunos SET sit = 'AF' WHERE mg <6 and mg >3")
cursor.execute("UPDATE alunos SET sit = 'REprov' WHERE mg < 3")
cursor.execute("SELECT * FROM alunos")
print(cursor.fetchall())
cursor.execute("SELECT * FROM alunos")